language: python

sudo: required
dist: trusty

env:
  - TEST_SUITE=basic OS_TYPE=debian8
  - TEST_SUITE=extraserver OS_TYPE=debian8
  - TEST_SUITE=extrasettings OS_TYPE=debian8
  - TEST_SUITE=basicserver OS_TYPE=debian8
  - TEST_SUITE=basicsettings OS_TYPE=debian8
  - TEST_SUITE=basic OS_TYPE=debian9
  - TEST_SUITE=extraserver OS_TYPE=debian9
  - TEST_SUITE=extrasettings OS_TYPE=debian9
  - TEST_SUITE=basicserver OS_TYPE=debian9
  - TEST_SUITE=basicsettings OS_TYPE=debian9
  - TEST_SUITE=basic OS_TYPE=ubuntu16.04
  - TEST_SUITE=extraserver OS_TYPE=ubuntu16.04
  - TEST_SUITE=extrasettings OS_TYPE=ubuntu16.04
  - TEST_SUITE=basicserver OS_TYPE=ubuntu16.04
  - TEST_SUITE=basicsettings OS_TYPE=ubuntu16.04


services:
  - docker

python:
  - "2.7"


before_install:
  - chmod +x .travis/run.sh
  - chmod +x .travis/install.sh

before_script:
  - docker build -t ndts .travis/${OS_TYPE}
  - docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts
  - .travis/install.sh ${OS_TYPE}

script:
  - .travis/run.sh $TEST_SUITE

after-script:
  - docker stop ndts
  - docker rm ndts
