language: python
dist: xenial

env:
  - TEST="flake8"
  - TEST=basic OS=debian9 PY=2
  - TEST=extrasettings OS=debian9 PY=2
  - TEST=extraserver OS=debian9 PY=2
  - TEST=basicserver OS=debian9 PY=2
  - TEST=basicsettings OS=debian9 PY=2
  - TEST=basic OS=debian9 PY=3
  - TEST=extrasettings OS=debian9 PY=3
  - TEST=extraserver OS=debian9 PY=3
  - TEST=basicserver OS=debian9 PY=3
  - TEST=basicsettings OS=debian9 PY=3
  - TEST=basic OS=debian8 PY=2
  - TEST=extrasettings OS=debian8 PY=2
  - TEST=extraserver OS=debian8 PY=2
  - TEST=basicserver OS=debian8 PY=2
  - TEST=basicsettings OS=debian8 PY=2
  # - TEST=basic OS=ubuntu18.04 PY=2
  # - TEST=extrasettings OS=ubuntu18.04 PY=2
  # - TEST=extraserver OS=ubuntu18.04 PY=2
  # - TEST=basicserver OS=ubuntu18.04 PY=2
  # - TEST=basicsettings OS=ubuntu18.04 PY=2
  # - TEST=basic OS=ubuntu18.04 PY=3
  # - TEST=extrasettings OS=ubuntu18.04 PY=3
  # - TEST=extraserver OS=ubuntu18.04 PY=3
  # - TEST=basicserver OS=ubuntu18.04 PY=3
  # - TEST=basicsettings OS=ubuntu18.04 PY=3
  # - TEST=basic OS=ubuntu16.04 PY=2
  # - TEST=extrasettings OS=ubuntu16.04 PY=2
  # - TEST=extraserver OS=ubuntu16.04 PY=2
  # - TEST=basicserver OS=ubuntu16.04 PY=2
  # - TEST=basicsettings OS=ubuntu16.04 PY=2
  # - TEST=basic OS=ubuntu16.04 PY=3
  # - TEST=extrasettings OS=ubuntu16.04 PY=3
  # - TEST=extraserver OS=ubuntu16.04 PY=3
  # - TEST=basicserver OS=ubuntu16.04 PY=3
  # - TEST=basicsettings OS=ubuntu16.04 PY=3
  # - TEST=basic OS=debian8 PY=3
  # - TEST=extrasettings OS=debian8 PY=3
  # - TEST=extraserver OS=debian8 PY=3
  # - TEST=basicserver OS=debian8 PY=3
  # - TEST=basicsettings OS=debian8 PY=3
  # - TEST=basic OS=debian10 PY=3
  # - TEST=extrasettings OS=debian10 PY=3
  # - TEST=extraserver OS=debian10 PY=3
  # - TEST=basicserver OS=debian10 PY=3
  # - TEST=basicsettings OS=debian10 PY=3
  # - TEST=basic OS=debian10 PY=2
  # - TEST=extrasettings OS=debian10 PY=2
  # - TEST=extraserver OS=debian10 PY=2
  # - TEST=basicserver OS=debian10 PY=2
  # - TEST=basicsettings OS=debian10 PY=2


services:
  - docker


before_install:
  - if [ $TEST == "flake8" ]; then sudo apt-get update -qq ; fi
  - if [ $TEST == "flake8" ]; then sudo pip install flake8; fi
  - if [ $TEST != "flake8" ]; then chmod +x .travis/run.sh; fi
  - if [ $TEST != "flake8" ]; then chmod +x .travis/install.sh; fi

before_script:
  - if [ $TEST != "flake8" ]; then docker build -t ndts .travis/${OS}_py${PY}; fi
  - if [ $TEST != "flake8" ]; then docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts; fi
  - if [ $TEST != "flake8" ]; then .travis/install.sh ${OS} ${PY}; fi

script:
  - if [ $TEST != "flake8" ]; then .travis/run.sh ${TEST} ${PY}; fi
  - if [ $TEST == "flake8" ]; then flake8; fi

after-script:
  - if [ $TEST != "flake8" ]; then docker stop ndts; fi
  - if [ $TEST != "flake8" ]; then docker rm ndts; fi
