language: python

sudo: required
dist: trusty
group: deprecated-2017Q2

env:
  - TEST="flake8"
  - TEST=basic OS_TYPE=debian9 PYTHON=2
  - TEST=extrasettings OS_TYPE=debian9 PYTHON=2
  - TEST=extraserver OS_TYPE=debian9 PYTHON=2
  - TEST=basicserver OS_TYPE=debian9 PYTHON=2
  - TEST=basicsettings OS_TYPE=debian9 PYTHON=2
  - TEST=basic OS_TYPE=debian8 PYTHON=2
  - TEST=extrasettings OS_TYPE=debian8 PYTHON=2
  - TEST=extraserver OS_TYPE=debian8 PYTHON=2
  - TEST=basicserver OS_TYPE=debian8 PYTHON=2
  - TEST=basicsettings OS_TYPE=debian8 PYTHON=2
  - TEST=basic OS_TYPE=ubuntu18.04 PYTHON=2
  - TEST=extrasettings OS_TYPE=ubuntu18.04 PYTHON=2
  - TEST=extraserver OS_TYPE=ubuntu18.04 PYTHON=2
  - TEST=basicserver OS_TYPE=ubuntu18.04 PYTHON=2
  - TEST=basicsettings OS_TYPE=ubuntu18.04 PYTHON=2
  # - TEST=basic OS_TYPE=ubuntu16.04 PYTHON=2
  # - TEST=extrasettings OS_TYPE=ubuntu16.04 PYTHON=2
  # - TEST=extraserver OS_TYPE=ubuntu16.04 PYTHON=2
  # - TEST=basicserver OS_TYPE=ubuntu16.04 PYTHON=2
  # - TEST=basicsettings OS_TYPE=ubuntu16.04 PYTHON=2
  # - TEST=basic OS_TYPE=debian8 PYTHON=3
  # - TEST=extrasettings OS_TYPE=debian8 PYTHON=3
  # - TEST=extraserver OS_TYPE=debian8 PYTHON=3
  # - TEST=basicserver OS_TYPE=debian8 PYTHON=3
  # - TEST=basicsettings OS_TYPE=debian8 PYTHON=3
  # - TEST=basic OS_TYPE=debian9 PYTHON=3
  # - TEST=extrasettings OS_TYPE=debian9 PYTHON=3
  # - TEST=extraserver OS_TYPE=debian9 PYTHON=3
  # - TEST=basicserver OS_TYPE=debian9 PYTHON=3
  # - TEST=basicsettings OS_TYPE=debian9 PYTHON=3
  # - TEST=basic OS_TYPE=ubuntu16.04 PYTHON=3
  # - TEST=extrasettings OS_TYPE=ubuntu16.04 PYTHON=3
  # - TEST=extraserver OS_TYPE=ubuntu16.04 PYTHON=3
  # - TEST=basicserver OS_TYPE=ubuntu16.04 PYTHON=3
  # - TEST=basicsettings OS_TYPE=ubuntu16.04 PYTHON=3
  # - TEST=basic OS_TYPE=ubuntu18.04 PYTHON=3
  # - TEST=extrasettings OS_TYPE=ubuntu18.04 PYTHON=3
  # - TEST=extraserver OS_TYPE=ubuntu18.04 PYTHON=3
  # - TEST=basicserver OS_TYPE=ubuntu18.04 PYTHON=3
  # - TEST=basicsettings OS_TYPE=ubuntu18.04 PYTHON=3


services:
  - docker


before_install:
  - if [ $TEST == "flake8" ]; then sudo apt-get update -qq ; fi
  - if [ $TEST == "flake8" ]; then sudo pip install flake8; fi
  - if [ $TEST != "flake8" ]; then chmod +x .travis/run.sh; fi
  - if [ $TEST != "flake8" ]; then chmod +x .travis/install.sh; fi

before_script:
  - if [ $TEST != "flake8" ]; then docker build -t ndts .travis/${OS_TYPE}_py${PYTHON}; fi
  - if [ $TEST != "flake8" ]; then docker run  --name  ndts -d -it -v `pwd`:/home/tango  ndts; fi
  - if [ $TEST != "flake8" ]; then .travis/install.sh ${OS_TYPE} ${PYTHON}; fi

script:
  - if [ $TEST != "flake8" ]; then .travis/run.sh ${TEST} ${PYTHON}; fi
  - if [ $TEST == "flake8" ]; then flake8; fi

after-script:
  - if [ $TEST != "flake8" ]; then docker stop ndts; fi
  - if [ $TEST != "flake8" ]; then docker rm ndts; fi
